name: Download chainguard adoptium-jre-17

on:
  workflow_dispatch: # 允許手動觸發

jobs:
  download_and_export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: |
          # 下載 cgr.dev/chainguard/adoptium-jre:adoptium-openjdk-17.0.19 映像檔
          docker pull cgr.dev/chainguard/adoptium-jre:adoptium-openjdk-17.0.19

      - name: Save Docker Image to Tarball
        run: |
          # 將 image 匯出為 .tar 檔案 (適用於離線匯入)
          docker save -o chainguard-adoptium-jre-17.tar cgr.dev/chainguard/adoptium-jre:adoptium-openjdk-17.0.19

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chainguard-adoptium-jre-17-tarball
          path: chainguard-adoptium-jre-17.tar
          retention-days: 7 # 產生的檔案保留 7 天