name: Download alpine 3.22

on:
  workflow_dispatch: # 允許手動觸發

jobs:
  download_and_export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker Image
        run: |
          # 下載 alpine:3.22 映像檔
          docker pull alpine:3.22

      - name: Save Docker Image to Tarball
        run: |
          # 將 image 匯出為 .tar 檔案 (適用於離線匯入)
          docker save -o alpine-3.22.tar alpine:3.22

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-3.22-tarball
          path: alpine-3.22.tar
          retention-days: 7 # 產生的檔案保留 7 天
